const { PDFDocument, rgb, StandardFonts } = require('pdf-lib');
const { query } = require('../db');

// ─── Helper: draw text ────────────────────────────────────────────────────────
const hex = (h) => {
  const r = parseInt(h.slice(1, 3), 16) / 255;
  const g = parseInt(h.slice(3, 5), 16) / 255;
  const b = parseInt(h.slice(5, 7), 16) / 255;
  return rgb(r, g, b);
};

const COLORS = {
  primary: hex('#1a2544'),
  accent:  hex('#f5a623'),
  white:   rgb(1, 1, 1),
  gray:    hex('#888888'),
  light:   hex('#f5f5f5'),
  green:   hex('#16a34a'),
  red:     hex('#dc2626'),
};

// ─── Header for all PDFs ──────────────────────────────────────────────────────
const drawHeader = async (page, fonts, schoolName, title) => {
  const { width } = page.getSize();
  // Header bg
  page.drawRectangle({ x: 0, y: page.getSize().height - 70, width, height: 70, color: COLORS.primary });
  // School name
  page.drawText('AKKHOR™', { x: 30, y: page.getSize().height - 28, size: 20, font: fonts.bold, color: COLORS.accent });
  page.drawText(schoolName, { x: 30, y: page.getSize().height - 48, size: 10, font: fonts.regular, color: COLORS.white });
  // Title (right side)
  page.drawText(title, { x: width - 30 - title.length * 6, y: page.getSize().height - 38, size: 14, font: fonts.bold, color: COLORS.white });
  // Accent bar
  page.drawRectangle({ x: 0, y: page.getSize().height - 73, width, height: 3, color: COLORS.accent });
};

// ─── Footer ───────────────────────────────────────────────────────────────────
const drawFooter = (page, fonts, pageNum) => {
  const { width } = page.getSize();
  page.drawRectangle({ x: 0, y: 0, width, height: 35, color: COLORS.light });
  page.drawText(`Generated by Akkhor School Management System`, { x: 30, y: 12, size: 8, font: fonts.regular, color: COLORS.gray });
  page.drawText(`Page ${pageNum}`, { x: width - 60, y: 12, size: 8, font: fonts.regular, color: COLORS.gray });
  page.drawText(new Date().toLocaleDateString(), { x: width / 2 - 30, y: 12, size: 8, font: fonts.regular, color: COLORS.gray });
};

// ─── 1. Fee Receipt PDF ────────────────────────────────────────────────────────
const generateFeeReceipt = async (feeId, schoolId) => {
  const result = await query(`
    SELECT f.*, CONCAT(u.first_name,' ',u.last_name) as student_name,
      c.name as class_name, c.section, s.roll_number,
      sc.name as school_name
    FROM fee_collections f
    JOIN students st ON f.student_id = st.id
    JOIN users u ON st.user_id = u.id
    LEFT JOIN classes c ON st.class_id = c.id
    JOIN schools sc ON f.school_id = sc.id
    LEFT JOIN students s ON f.student_id = s.id
    WHERE f.id = $1 AND f.school_id = $2
  `, [feeId, schoolId]);

  if (!result.rows.length) throw new Error('Fee record not found');
  const fee = result.rows[0];

  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595, 400]);
  const fonts = {
    bold: await pdfDoc.embedFont(StandardFonts.HelveticaBold),
    regular: await pdfDoc.embedFont(StandardFonts.Helvetica),
  };
  const { width, height } = page.getSize();

  // Header
  await drawHeader(page, fonts, fee.school_name, 'FEE RECEIPT');

  // Receipt box
  page.drawRectangle({ x: 30, y: height - 250, width: width - 60, height: 160, color: COLORS.light, borderColor: COLORS.gray, borderWidth: 0.5 });

  // Receipt number
  page.drawText(`Receipt No: #${fee.id.slice(0, 8).toUpperCase()}`, { x: 45, y: height - 100, size: 11, font: fonts.bold, color: COLORS.primary });
  const statusColor = fee.status === 'Paid' ? COLORS.green : COLORS.red;
  page.drawText(fee.status.toUpperCase(), { x: width - 100, y: height - 100, size: 12, font: fonts.bold, color: statusColor });

  // Fields
  const fields = [
    ['Student Name', fee.student_name],
    ['Class', `${fee.class_name || '-'} - Section ${fee.section || '-'}`],
    ['Roll Number', fee.roll_number || '-'],
    ['Fee Type', fee.fee_type],
    ['Payment Method', fee.payment_method || 'Cash'],
    ['Date', new Date(fee.created_at).toLocaleDateString()],
  ];

  fields.forEach(([label, value], i) => {
    const y = height - 130 - i * 22;
    page.drawText(`${label}:`, { x: 45, y, size: 9, font: fonts.regular, color: COLORS.gray });
    page.drawText(value, { x: 200, y, size: 9, font: fonts.regular, color: COLORS.primary });
  });

  // Amount box
  page.drawRectangle({ x: 30, y: height - 290, width: width - 60, height: 40, color: COLORS.primary });
  page.drawText('Total Amount:', { x: 45, y: height - 275, size: 11, font: fonts.regular, color: COLORS.white });
  page.drawText(`$${parseFloat(fee.amount).toFixed(2)}`, { x: width - 120, y: height - 275, size: 16, font: fonts.bold, color: COLORS.accent });

  // Signature line
  page.drawLine({ start: { x: 45, y: height - 340 }, end: { x: 180, y: height - 340 }, thickness: 0.5, color: COLORS.gray });
  page.drawText('Authorized Signature', { x: 75, y: height - 355, size: 8, font: fonts.regular, color: COLORS.gray });

  drawFooter(page, fonts, 1);

  const pdfBytes = await pdfDoc.save();
  return Buffer.from(pdfBytes);
};

// ─── 2. Attendance Sheet PDF ───────────────────────────────────────────────────
const generateAttendanceSheet = async (classId, month, year, schoolId) => {
  const classResult = await query(
    'SELECT c.*, sc.name as school_name FROM classes c JOIN schools sc ON c.school_id = sc.id WHERE c.id = $1 AND c.school_id = $2',
    [classId, schoolId]
  );
  if (!classResult.rows.length) throw new Error('Class not found');
  const cls = classResult.rows[0];

  const attendanceResult = await query(`
    SELECT a.*, CONCAT(u.first_name,' ',u.last_name) as student_name, s.roll_number
    FROM attendance a
    JOIN students s ON a.student_id = s.id
    JOIN users u ON s.user_id = u.id
    WHERE a.class_id = $1 AND EXTRACT(MONTH FROM a.date) = $2 AND EXTRACT(YEAR FROM a.date) = $3 AND a.school_id = $4
    ORDER BY s.roll_number, a.date
  `, [classId, month, year, schoolId]);

  const daysInMonth = new Date(year, month, 0).getDate();
  const monthNames = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

  // Group by student
  const students = {};
  attendanceResult.rows.forEach(row => {
    if (!students[row.student_id]) {
      students[row.student_id] = { name: row.student_name, roll: row.roll_number, days: {} };
    }
    students[row.student_id].days[new Date(row.date).getDate()] = row.status;
  });

  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([842, 595]); // A4 landscape
  const fonts = {
    bold: await pdfDoc.embedFont(StandardFonts.HelveticaBold),
    regular: await pdfDoc.embedFont(StandardFonts.Helvetica),
  };
  const { width, height } = page.getSize();

  await drawHeader(page, fonts, cls.school_name, `ATTENDANCE - Class ${cls.name} ${cls.section} | ${monthNames[month-1]} ${year}`);

  // Table header
  const colWidth = Math.min(15, (width - 200) / daysInMonth);
  const startX = 180;
  const startY = height - 90;

  page.drawText('Student Name', { x: 30, y: startY + 5, size: 8, font: fonts.bold, color: COLORS.primary });
  page.drawText('Roll', { x: 140, y: startY + 5, size: 8, font: fonts.bold, color: COLORS.primary });

  for (let d = 1; d <= daysInMonth; d++) {
    page.drawText(d.toString(), {
      x: startX + (d - 1) * colWidth + colWidth / 2 - 4,
      y: startY + 5, size: 7, font: fonts.bold, color: COLORS.primary
    });
  }

  // Draw student rows
  Object.values(students).slice(0, 25).forEach((student, i) => {
    const y = startY - 20 - i * 18;
    const bg = i % 2 === 0 ? COLORS.white : COLORS.light;
    page.drawRectangle({ x: 20, y: y - 5, width: width - 40, height: 18, color: bg });
    page.drawText(student.name.slice(0, 20), { x: 30, y, size: 7, font: fonts.regular, color: COLORS.primary });
    page.drawText(student.roll || '-', { x: 140, y, size: 7, font: fonts.regular, color: COLORS.gray });

    for (let d = 1; d <= daysInMonth; d++) {
      const status = student.days[d];
      const x = startX + (d - 1) * colWidth + colWidth / 2 - 4;
      const symbol = status === 'present' ? '✓' : status === 'absent' ? '✗' : '-';
      const color = status === 'present' ? COLORS.green : status === 'absent' ? COLORS.red : COLORS.gray;
      page.drawText(symbol, { x, y, size: 7, font: fonts.bold, color });
    }
  });

  // Summary
  const totalStudents = Object.keys(students).length;
  page.drawText(`Total Students: ${totalStudents}`, { x: 30, y: 50, size: 9, font: fonts.regular, color: COLORS.gray });

  drawFooter(page, fonts, 1);
  return Buffer.from(await pdfDoc.save());
};

// ─── 3. Student Report Card PDF ────────────────────────────────────────────────
const generateReportCard = async (studentId, schoolId) => {
  const studentResult = await query(`
    SELECT st.*, CONCAT(u.first_name,' ',u.last_name) as full_name,
      u.gender, u.date_of_birth, u.email, u.photo_url,
      c.name as class_name, c.section, sc.name as school_name
    FROM students st
    JOIN users u ON st.user_id = u.id
    LEFT JOIN classes c ON st.class_id = c.id
    JOIN schools sc ON st.school_id = sc.id
    WHERE st.id = $1 AND st.school_id = $2
  `, [studentId, schoolId]);

  if (!studentResult.rows.length) throw new Error('Student not found');
  const student = studentResult.rows[0];

  const resultsResult = await query(`
    SELECT er.*, e.name as exam_name, s.name as subject_name,
      eg.grade_name, eg.grade_point
    FROM exam_results er
    JOIN exams e ON er.exam_id = e.id
    JOIN subjects s ON e.subject_id = s.id
    LEFT JOIN exam_grades eg ON er.grade_id = eg.id
    WHERE er.student_id = $1 AND er.school_id = $2
    ORDER BY e.exam_date DESC
    LIMIT 20
  `, [studentId, schoolId]);

  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595, 842]); // A4 portrait
  const fonts = {
    bold: await pdfDoc.embedFont(StandardFonts.HelveticaBold),
    regular: await pdfDoc.embedFont(StandardFonts.Helvetica),
  };
  const { width, height } = page.getSize();

  await drawHeader(page, fonts, student.school_name, 'STUDENT REPORT CARD');

  // Student info section
  page.drawRectangle({ x: 30, y: height - 200, width: width - 60, height: 110, color: COLORS.light });
  const infoFields = [
    ['Student Name', student.full_name],
    ['Class', `${student.class_name || '-'} - Section ${student.section || '-'}`],
    ['Roll Number', student.roll_number || '-'],
    ['Admission No', student.admission_no || '-'],
    ['Gender', student.gender || '-'],
  ];
  infoFields.forEach(([label, value], i) => {
    const col = i < 3 ? 0 : 1;
    const row = i < 3 ? i : i - 3;
    const x = col === 0 ? 45 : width / 2 + 15;
    const y = height - 115 - row * 22;
    page.drawText(`${label}:`, { x, y, size: 9, font: fonts.regular, color: COLORS.gray });
    page.drawText(value, { x: x + 100, y, size: 9, font: fonts.bold, color: COLORS.primary });
  });

  // Results table
  if (resultsResult.rows.length > 0) {
    page.drawText('Examination Results', { x: 30, y: height - 230, size: 13, font: fonts.bold, color: COLORS.primary });
    page.drawRectangle({ x: 30, y: height - 260, width: width - 60, height: 25, color: COLORS.primary });
    const headers = ['Exam', 'Subject', 'Marks', 'Grade', 'Points'];
    const colWidths = [160, 140, 70, 60, 65];
    let cx = 40;
    headers.forEach((h, i) => {
      page.drawText(h, { x: cx, y: height - 250, size: 9, font: fonts.bold, color: COLORS.white });
      cx += colWidths[i];
    });

    resultsResult.rows.slice(0, 15).forEach((r, i) => {
      const y = height - 275 - i * 22;
      const bg = i % 2 === 0 ? COLORS.white : COLORS.light;
      page.drawRectangle({ x: 30, y: y - 8, width: width - 60, height: 22, color: bg });
      const vals = [r.exam_name, r.subject_name, `${r.marks_obtained || '-'}/100`, r.grade_name || '-', r.grade_point?.toString() || '-'];
      cx = 40;
      vals.forEach((v, j) => {
        const color = j === 3 && r.grade_name ? COLORS.green : COLORS.primary;
        page.drawText((v || '-').toString().slice(0, 20), { x: cx, y: y, size: 8, font: fonts.regular, color });
        cx += colWidths[j];
      });
    });

    // Total / Average
    const totalMarks = resultsResult.rows.reduce((sum, r) => sum + (parseFloat(r.marks_obtained) || 0), 0);
    const avgMarks = (totalMarks / resultsResult.rows.length).toFixed(1);
    const summaryY = height - 275 - resultsResult.rows.length * 22 - 20;
    page.drawRectangle({ x: 30, y: summaryY - 8, width: width - 60, height: 24, color: COLORS.accent });
    page.drawText(`Average Marks: ${avgMarks}%`, { x: 45, y: summaryY, size: 10, font: fonts.bold, color: COLORS.primary });
  } else {
    page.drawText('No exam results recorded yet.', { x: 30, y: height - 240, size: 10, font: fonts.regular, color: COLORS.gray });
  }

  // Signature area
  page.drawLine({ start: { x: 60, y: 80 }, end: { x: 200, y: 80 }, thickness: 0.5, color: COLORS.gray });
  page.drawLine({ start: { x: width - 200, y: 80 }, end: { x: width - 60, y: 80 }, thickness: 0.5, color: COLORS.gray });
  page.drawText('Class Teacher', { x: 100, y: 65, size: 9, font: fonts.regular, color: COLORS.gray });
  page.drawText('Principal', { x: width - 160, y: 65, size: 9, font: fonts.regular, color: COLORS.gray });

  drawFooter(page, fonts, 1);
  return Buffer.from(await pdfDoc.save());
};

// ─── 4. School Overview Report ─────────────────────────────────────────────────
const generateSchoolReport = async (schoolId) => {
  const [students, teachers, fees, attendance] = await Promise.all([
    query('SELECT COUNT(*) FROM students WHERE school_id = $1', [schoolId]),
    query('SELECT COUNT(*) FROM teachers WHERE school_id = $1', [schoolId]),
    query('SELECT COALESCE(SUM(amount),0) as total, COUNT(*) FILTER(WHERE status=\'Paid\') as paid, COUNT(*) FILTER(WHERE status=\'Due\') as due FROM fee_collections WHERE school_id = $1', [schoolId]),
    query('SELECT COUNT(*) FILTER(WHERE status=\'present\') as present, COUNT(*) as total FROM attendance WHERE school_id = $1 AND date >= NOW() - INTERVAL \'30 days\'', [schoolId]),
  ]);
  const school = await query('SELECT * FROM schools WHERE id = $1', [schoolId]);
  const s = school.rows[0];

  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595, 500]);
  const fonts = {
    bold: await pdfDoc.embedFont(StandardFonts.HelveticaBold),
    regular: await pdfDoc.embedFont(StandardFonts.Helvetica),
  };
  const { width, height } = page.getSize();

  await drawHeader(page, fonts, s.name, 'SCHOOL OVERVIEW REPORT');

  const stats = [
    { label: 'Total Students', value: students.rows[0].count, color: COLORS.green },
    { label: 'Total Teachers', value: teachers.rows[0].count, color: COLORS.primary },
    { label: 'Fee Collected', value: `$${parseFloat(fees.rows[0].total).toFixed(0)}`, color: COLORS.accent },
    { label: 'Attendance (30d)', value: `${attendance.rows[0].total > 0 ? Math.round((attendance.rows[0].present / attendance.rows[0].total) * 100) : 0}%`, color: COLORS.green },
  ];

  const boxW = (width - 80) / 4;
  stats.forEach((stat, i) => {
    const x = 30 + i * (boxW + 10);
    page.drawRectangle({ x, y: height - 180, width: boxW, height: 60, color: stat.color });
    page.drawText(stat.value.toString(), { x: x + 10, y: height - 142, size: 18, font: fonts.bold, color: COLORS.white });
    page.drawText(stat.label, { x: x + 10, y: height - 162, size: 8, font: fonts.regular, color: COLORS.white });
  });

  page.drawText('Generated: ' + new Date().toLocaleString(), { x: 30, y: height - 210, size: 9, font: fonts.regular, color: COLORS.gray });

  drawFooter(page, fonts, 1);
  return Buffer.from(await pdfDoc.save());
};

module.exports = { generateFeeReceipt, generateAttendanceSheet, generateReportCard, generateSchoolReport };
